#spring server port
server:
  port: 4000

spring:
  application:
    name: doit

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/doit?serverTimezone=Asia/Seoul
    username: root
    password: 882614


secret:
  key: 5tL8bu7gWhFn9sZpQdXDz4bEAJc1TKhtu2oM6qVfwNixGsZo9Km3npRyFS3D4JuHzms


token:
  expire : 10800

